"use client";

import { createClient } from "@supabase/supabase-js";

// ⚙️ Instancia o Supabase Client
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

// 🪝 Hook principal
export function useSupabasePdf() {
  type FichaRpg = {
    personagem?: string;
    jogador?: string;
    agilidade?: string;
    intelecto?: string;
    vigor?: string;
    presenca?: string;
    origem?: string;
    classe?: string;
    nex?: string;
    pe_rodada?: string;
    deslocamento?: string;
    pvAtual?: string;
    pvAntigo?: string;
    peAtual?: string;
    peAntigo?: string;
    defesa?: string;
    defEquip?: string;
    defOutr?: string;
    sanidadeAtual?: string;
    sanidadeAntiga?: string;
    protecao?: string;
    resistencias?: string;
    atq1?: string;
    atq2?: string;
    atq3?: string;
    atq4?: string;
    atq5?: string;
    teste1?: string;
    teste2?: string;
    teste3?: string;
    teste4?: string;
    teste5?: string;
    dano1?: string;
    dano2?: string;
    dano3?: string;
    dano4?: string;
    dano5?: string;
    critico1?: string;
    critico2?: string;
    critico3?: string;
    critico4?: string;
    critico5?: string;
    dado1?: string;
    dado2?: string;
    dado3?: string;
    dado4?: string;
    dado5?: string;
    dado6?: string;
    dado7?: string;
    dado8?: string;
    dado9?: string;
    dado10?: string;
    dado11?: string;
    dado12?: string;
    dado13?: string;
    dado14?: string;
    dado15?: string;
    dado16?: string;
    dado17?: string;
    dado18?: string;
    dado19?: string;
    dado20?: string;
    dado21?: string;
    dado22?: string;
    dado23?: string;
    dado24?: string;
    dado25?: string;
    dado26?: string;
    dado27?: string;
    dado28?: string;
    bonus1?: string;
    bonus2?: string;
    bonus3?: string;
    bonus4?: string;
    bonus5?: string;
    bonus6?: string;
    bonus7?: string;
    bonus8?: string;
    bonus9?: string;
    bonus10?: string;
    bonus11?: string;
    bonus12?: string;
    bonus13?: string;
    bonus14?: string;
    bonus15?: string;
    bonus16?: string;
    bonus17?: string;
    bonus18?: string;
    bonus19?: string;
    bonus20?: string;
    bonus21?: string;
    bonus22?: string;
    bonus23?: string;
    bonus24?: string;
    bonus25?: string;
    bonus26?: string;
    bonus27?: string;
    bonus28?: string;
    treino1?: string;
    treino2?: string;
    treino3?: string;
    treino4?: string;
    treino5?: string;
    treino6?: string;
    treino7?: string;
    treino8?: string;
    treino9?: string;
    treino10?: string;
    treino11?: string;
    treino12?: string;
    treino13?: string;
    treino14?: string;
    treino15?: string;
    treino16?: string;
    treino17?: string;
    treino18?: string;
    treino19?: string;
    treino20?: string;
    treino21?: string;
    treino22?: string;
    treino23?: string;
    treino24?: string;
    treino25?: string;
    treino26?: string;
    treino27?: string;
    treino28?: string;
    outros1?: string;
    outros2?: string;
    outros3?: string;
    outros4?: string;
    outros5?: string;
    outros6?: string;
    outros7?: string;
    outros8?: string;
    outros9?: string;
    outros10?: string;
    outros11?: string;
    outros12?: string;
    outros13?: string;
    outros14?: string;
    outros15?: string;
    outros16?: string;
    outros17?: string;
    outros18?: string;
    outros19?: string;
    outros20?: string;
    outros21?: string;
    outros22?: string;
    outros23?: string;
    outros24?: string;
    outros25?: string;
    outros26?: string;
    outros27?: string;
    outros28?: string;
    habilidade1?: string;
    habilidade2?: string;
    habilidade3?: string;
    habilidade4?: string;
    habilidade5?: string;
    habilidade6?: string;
    habilidade7?: string;
    habilidade8?: string;
    habilidade9?: string;
    habilidade10?: string;
    habilidade11?: string;
    habilidade12?: string;
    habilidade13?: string;
    habilidade14?: string;
    habilidade15?: string;
    habilidade16?: string;
    habilidade17?: string;
    habilidade18?: string;
    habilidade19?: string;
    habilidade20?: string;
    custo1?: string;
    custo2?: string;
    custo3?: string;
    custo4?: string;
    custo5?: string;
    custo6?: string;
    custo7?: string;
    custo8?: string;
    custo9?: string;
    custo10?: string;
    custo11?: string;
    custo12?: string;
    custo13?: string;
    custo14?: string;
    custo15?: string;
    custo16?: string;
    custo17?: string;
    custo18?: string;
    custo19?: string;
    custo20?: string;
    p1?: string;
    p2?: string;
    p3?: string;
    p4?: string;
    p5?: string;
    p6?: string;
    p7?: string;
    p8?: string;
    p9?: string;
    p10?: string;
    p11?: string;
    p12?: string;
    p13?: string;
    p14?: string;
    p15?: string;
    p16?: string;
    p17?: string;
    p18?: string;
    p19?: string;
    p20?: string;
    desc1?: string;
    desc2?: string;
    desc3?: string;
    desc4?: string;
    desc5?: string;
    desc6?: string;
    desc7?: string;
    desc8?: string;
    desc9?: string;
    desc10?: string;
    desc11?: string;
    desc12?: string;
    desc13?: string;
    desc14?: string;
    desc15?: string;
    desc16?: string;
    desc17?: string;
    desc18?: string;
    desc19?: string;
    desc20?: string;
    item1?: string;
    item2?: string;
    cat1?: string;
    cat2?: string;
    cat3?: string;
    cat4?: string;
    cat5?: string;
    cat6?: string;
    cat7?: string;
    cat8?: string;
    cat9?: string;
    cat10?: string;
    cat11?: string;
    item12?: string;
    item3?: string;
    item4?: string;
    item5?: string;
    item6?: string;
    item7?: string;
    item8?: string;
    item9?: string;
    item10?: string;
    item11?: string;
    item13?: string;
    item14?: string;
    item15?: string;
    item16?: string;
    item17?: string;
    item18?: string;
    item19?: string;
    item20?: string;
    item21?: string;
    item22?: string;
    pontosPrestigio?: string;
    patente?: string;
    limiteItens?: string;
    limiteItens2?: string;
    limiteItens3?: string;
    limiteItens4?: string;
    limiteCredito?: string;
    cargaMax?: string;
    cargaMax2?: string;
    naoSei?: string;
    cat12?: string;
    cat13?: string;
    cat14?: string;
    cat15?: string;
    cat16?: string;
    cat17?: string;
    cat18?: string;
    cat19?: string;
    cat20?: string;
    cat21?: string;
    cat22?: string;
    aparencia1?: string;
    aparencia2?: string;
    aparencia3?: string;
    aparencia4?: string;
    aparencia5?: string;
    personalidade1?: string;
    personalidade2?: string;
    personalidade3?: string;
    personalidade4?: string;
    personalidade5?: string;
    historico1?: string;
    historico2?: string;
    historico3?: string;
    historico4?: string;
    historico5?: string;
    objetivo1?: string;
    objetivo2?: string;
    objetivo3?: string;
    objetivo4?: string;
    objetivo5?: string;
    profissao?: string;
    dtRituais?: string;
    forca?: string;
    espaco1?: string;
    espaco2?: string;
    espaco3?: string;
    espaco4?: string;
    espaco5?: string;
    espaco6?: string;
    espaco7?: string;
    espaco8?: string;
    espaco9?: string;
    espaco10?: string;
    espaco11?: string;
    espaco12?: string;
    espaco13?: string;
    espaco14?: string;
    espaco15?: string;
    espaco16?: string;
    espaco17?: string;
    espaco18?: string;
    espaco19?: string;
    espaco20?: string;
    espaco21?: string;
    espaco22?: string;
  };

  // --- Salvar ficha no Supabase
  async function savePdfData(fields: FichaRpg) {
    const { data, error } = await supabase.from("ficha").insert([
      {
        attributes: fields,
      },
    ]);

    if (error) {
      console.error("Erro ao salvar ficha:", error);
      throw error;
    }

    return data;
  }

  // --- Buscar ficha
  async function getPdfData(sheetId: string) {
    const { data, error } = await supabase
      .from("ficha")
      .select("attributes")
      .eq("id", sheetId)
      .single();

    if (error) {
      console.error("Erro ao buscar ficha:", error);
      throw error;
    }

    return data?.attributes as FichaRpg | null;
  }

  return { savePdfData, getPdfData };
}
